apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: microservices
  region: eu-west-2

vpc:
  subnets:
    private:
      eu-west-1a: { id: subnet-0463a2c98865d50f0 }
      eu-west-1b: { id: subnet-0dd1e8399da23aeef }
      eu-west-1c: { id: subnet-04da2a26f6679973b }


nodeGroups:
  - name: nodegroup-worker1
    labels: { role: workers }
    instanceType: t3.large
    desiredCapacity: 2
    privateNetworking: true

   
fargateProfiles:
  - name: microservices
    selectors:
      # All workloads in the "microservices-*" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: microservices-*
        labels:
          env: serverless
