####Deployment####
appName: productcatalog
appImage: slimfit
appReplicas: 1
appVersion: 0.1.0
containerPort: 3550
containerEnvVariables:
- name: PORT
  value: "3550"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"
namespace: microservices-development
serviceAccountName: default
portName: grpc

####Service#####
serviceType: ClusterIP
servicePort: 3550
targetPort: 3550