####Deployment####
appName: servicename
appImage: gcr.io/google-samples/microservices-demo
appService: cartservice
appReplicas: 1
appVersion: v0.3.9
containerPort: 8080
containerEnvVariables:
- name: Env_Var_One
  value: "7"
- name: Env_Var_Two
  value: "1"
- name: Env_Var_Three
  value: "1"
- name: Env_Var_Four
  value: "1"
namespace: default
reqCPU: 100m
reqMem: 128Mi
limitCPU: 200m
limitMem: 256Mi
serviceAccountName: default
portName: grpc

####Service#####
serviceType: ClusterIP
servicePort: 8080
targetPort: 8080
