####Deployment####
appName: checkoutservice
appImage: gcr.io/google-samples/microservices-demo
appReplicas: 1
appVersion: v0.4.1
containerPort: 5050
containerEnvVariables:
- name: PORT
  value: "5050"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: "productcatalogservice:3550"
- name: SHIPPING_SERVICE_ADDR
  value: "shippingservice:50051"
- name: PAYMENT_SERVICE_ADDR
  value: "paymentservice:50051"
- name: EMAIL_SERVICE_ADDR
  value: "emailservice:5000"
- name: CURRENCY_SERVICE_ADDR
  value: "currencyservice:7000"
- name: CART_SERVICE_ADDR
  value: "cartservice:7070"
- name: DISABLE_STATS
  value: "1"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
serviceAccountName: default
portName: grpc

####Service#####
serviceType: ClusterIP
servicePort: 5050
targetPort: 5050