####Deployment####
appName: paymentservice
appImage: gcr.io/google-samples/microservices-demo
appReplicas: 1
#appVersion: v0.4.1
containerPort: 50051
containerEnvVariables:
- name: PORT
  value: "50051"
- name: DISABLE_TRACING
  value: "1"
- name: DISABLE_PROFILER
  value: "1"
- name: DISABLE_DEBUGGER
  value: "1"
namespace: microservices-development
serviceAccountName: default
portName: grpc

####Service#####
serviceType: ClusterIP
servicePort: 50051
targetPort: 50051